name: indicadores_economicos

on:
  push:
    branches: [ feature/andreskyjas ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
  
    steps:
      - name: paso1 - ubicacion ruta base
        uses: actions/checkout@v4
      - name: paso2 - instalacion python 3.7.9
        uses: actions/setup-python@v5
        with:
            python-version: '>3.9' 
      - name: paso3 - crea entorno virtual
        run: python -m venv venv
      - name: paso3 - activar entorno virtual
        run: source venv/Scripts/activate   
      - name: paso3 - actualizar pip
        run: pip install --upgrade pip
      - name: paso4 - instalar dependencias
        run: pip install -e .
      - name: paso5 - ejecutar proyecto
        run: python src/actividad/ejecucion.py
      - name: paso6 - auto commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with: 
          commit_user_name: Andres Callejas
          commit_user_email: andres.callejas@iudigital.edu.co
          commit_author: andresfkyjas
  
